name: Android App APK Build

on:
  push:
    branches:
      - main
    paths:
        - app/**
        - assets/**
        - components/**
        - functions/**
        - app.json
        - eas.json
        - .forgejo/workflows/apk-build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          apt-get update && apt-get install -y jq

      - name: Get App Version
        id: version
        run: |
          echo "app_version=$(jq .version package.json -r)" >> $FORGEJO_OUTPUT

      - name: Get Commit SHA
        id: sha
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $FORGEJO_OUTPUT

      - name: Create output directory
        run: |
          mkdir -p ${{ forgejo.workspace }}/output
      
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: https://github.com/android-actions/setup-android@v3

      - name: Setup Expo
        uses: https://github.com/expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android app
        run: eas build --clear-cache --platform android --profile preview --local --output ${{ forgejo.workspace }}/output/app-release.apk

      - name: Publish Release
        uses: actions/forgejo-release@v2.7.3
        env:
          GITHUB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        with:
          direction: upload
          prerelease: false
          url: https://git.stefdp.com
          repo: Stef/Clock-app
          token: ${{ secrets.FORGEJO_TOKEN }}
          tag: "v${{ steps.version.outputs.app_version }}-${{ steps.sha.outputs.commit_sha }}"
          release-dir: ${{ forgejo.workspace }}/output